# SPDX-FileCopyrightText: Josef Andersson
#
# SPDX-License-Identifier: CC0-1.0

# Description:
# This workflow runs MegaLinter to analyze your codebase for linting, security, and formatting issues.
# It uploads the results as artifacts and integrates with the GitHub Security tab.
#
# How to use:
# 1. Add the following to your workflow file:
#    jobs:
#      mega-linter:
#        uses: <orgname>/<reponame>/.github/workflows/<workflowname>.yml@main
#        with:
#          megalinter-config: "path/to/your/megalinter.yml" # Optional
#
# 2. Ensure your repository has a MegaLinter configuration file (e.g., `.megalinter.yml`).
#    If not, MegaLinter will use its default configuration.
#
# 3. The results will be available as artifacts and in the GitHub Security tab.
---
name: MegaLinter

on:
  workflow_call: # yamllint disable-line rule:truthy
    inputs:
      megalinter-config:
        description: "Path to the MegaLinter configuration file (e.g., .mega-linter.yml)"
        required: false
        default: "development/megalinter.yml"
        type: string
      egress-policy:
        description: "Egress policy for the Harden Runner step (e.g., audit, block)"
        required: false
        default: "audit"
        type: string

permissions:
  contents: read

jobs:
  megalinter:
    name: Megalinter analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    env:
      MEGALINTER_CONFIG: ${{ inputs.megalinter-config }} # Use the input value
    steps:
      - name: Harden GitHub runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: ${{ inputs.egress-policy }}
    
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 10

      - name: MegaLinter lint
        id: l
        uses: oxsecurity/megalinter@8fbdead70d1409964ab3d5afa885e18ee85388bb # v9.4.0

      - name: Archive MegaLinter artifacts
        if: always()
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
          retention-days: 5

      - name: Upload MegaLinter scan results to GitHub Security tab
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@68bde559dea0fdcac2102bfdf6230c5f70eb485e # v4.35.4
        with:
          sarif_file: "megalinter-reports/megalinter-report.sarif"
