# SPDX-FileCopyrightText: Josef Andersson
#
# SPDX-License-Identifier: CC0-1.0

# Description:
# This workflow runs MegaLinter to analyze your codebase for linting, security, and formatting issues.
# It uploads the results as artifacts and integrates with the GitHub Security tab.
#
# How to use:
# 1. Add the following to your workflow file:
#    jobs:
#      mega-linter:
#        uses: <orgname>/<reponame>/.github/workflows/<workflowname>.yml@main
#        with:
#          megalinter-config: "path/to/your/megalinter.yml" # Optional
#
# 2. Ensure your repository has a MegaLinter configuration file (e.g., `.megalinter.yml`).
#    If not, MegaLinter will use its default configuration.
#
# 3. The results will be available as artifacts and in the GitHub Security tab.
---
name: MegaLinter

on:
  workflow_call: # yamllint disable-line rule:truthy
    inputs:
      megalinter-config:
        description: "Path to the MegaLinter configuration file (e.g., .mega-linter.yml)"
        required: false
        default: "development/megalinter.yml"
        type: string
      egress-policy:
        description: "Egress policy for the Harden Runner step (e.g., audit, block)"
        required: false
        default: "audit"
        type: string

permissions:
  contents: read

jobs:
  megalinter:
    name: Megalinter analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    env:
      MEGALINTER_CONFIG: ${{ inputs.megalinter-config }} # Use the input value
    steps:
      - name: Harden GitHub runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: ${{ inputs.egress-policy }}
    
      - name: Checkout repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          fetch-depth: 10

      - name: MegaLinter lint
        id: l
        uses: oxsecurity/megalinter@ef3e84b8b836d76db562d0f3ed7da61e8fd538bc # v9.6.0

      - name: Archive MegaLinter artifacts
        if: always()
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
          retention-days: 5

      - name: Upload MegaLinter scan results to GitHub Security tab
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@f205ea1c3313d32999d8d6a48b4f6530d4437b38 # v4.37.4
        with:
          sarif_file: "megalinter-reports/megalinter-report.sarif"
